config/routes.rb
Rails.application.routes.draw do
  # changed for user profiles to appear
  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show, :index]

  # allows a user to like another user profile
  resources :users, only: :show do
    member do
      post 'toggle_favorite', to: "users#toggle_favorite"
    end
  end

  resources :shelf_games, only: [:index, :create, :update, :destroy]
  root to: 'games#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # If we decide to have user created shelves we should add :new and :create

  resources :games, only: [:index, :show] do
    resources :shelf_games, only: [:create, :update]

    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  # a user can like another user's profile
  acts_as_favoritor
  acts_as_favoritable

  has_many :reviews, dependent: :destroy
  has_many :shelf_games, dependent: :destroy
  has_many :games, through: :shelf_games
  has_one_attached :avatar

  validates :name, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_name,
    against: [ :name ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pundit
  before_action :verify_authorized, except: [:show, :toggle_favorite]
  # before_action :authenticate_user!, only: :toggle_favorite

  def toggle_favorite
    @user = User.find_by(id: params[:id])
    current_user.favorited?(@user)  ? current_user.unfavorite(@user) : current_user.favorite(@user)
    respond_to do |format|
      format.html
      format.js
    end
    authorize @user
  end

  def show
    @games = Game.all
    # users can click on other users reviews with this
    @user = User.find(params[:id])
    # users can follow other users
    @users = User.all
    @favorite_users = current_user.favorited_by_type('User')
    # shelf in the profile partial?
    @want_to_play = []
    @now_playing = []
    @completed = []
    @user.shelf_games.each do |shelf_game|
      case shelf_game.category
      when "want to play"
        @want_to_play << shelf_game
      when "now playing"
        @now_playing << shelf_game
      when "completed"
        @completed << shelf_game
      end
    end
    # group game by category then count them to add to the graph
    @game_per_category = @user.shelf_games.group_by{|game| game.category}
    @completed_count =  @game_per_category['completed'].to_a.count
    @now_playing_count =  @game_per_category['now playing'].to_a.count
    @want_to_play_count =  @game_per_category['want to play'].to_a.count
    @graph_array = [ @completed_count, @now_playing_count, @want_to_play_count ]
    authorize @user
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:avatar)
  end

end

app/views/users/_friends.html.erb
<div class="tab-content p-0"> </div>
<h1>Users</h1>
<div class="tab-pane fade active show" id="profile-friends">
  <%# <%= cl_image_tag(current_user.avatar.key) %>
  <%# <%current_user.avatar.attached? %>
  <div class="m-b-10"><b>My game shelf users(<%= @users.count %>)</b></div>
  <% @users.each do |user| %>
    <!-- this line needs to be put in the controller -->
    <div class="tab-pane fade active show" id="profile-friends">
      <ul class="friend-list clearfix">
        <li>
          <%= link_to user_path(user) do %>
            <%if user.avatar.attached?%>
              <div class="friend-img"> <%= cl_image_tag(user.avatar.key, class: "avatar") %>
              <% else %>
                <%= image_tag "gamepad.png", class: "avatar" %>
              <% end %>
            </div>
            <div class="friend-info">
              <h4><%= user.name %></h4>
            </div>
          </li>
        <% end %>
      <% end %>
    </div>
    <div class="col-4">
      <div class="tab-content p-0">
        <h1>Users</h1>
        <div class="tab-pane fade active show" id="profile-friends">
          <h5><b>My game shelf users(<%= @users.count %>)</b></h5>
          <% @users.each do |user| %>
            <!-- this line needs to be put in the controller -->
            <div class="tab-pane fade active show" id="profile-friends">
              <ul class="friend-list clearfix">
                <li>
                  <%= link_to user_path(user) do %>
                    <div class="friend-img"> <%= image_tag "avatar.png" %></div>
                    <div class="friend-info">
                      <h4><%= user.name %></h4>
                    </li>
                  <% end %>
                </ul>
                <!-- like button -->
                <%=link_to toggle_favorite_user_path(user), remote: true, method: :post do %>
                  <%= render 'users/like_button', user: user %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-2">
        <h3>Liked users</h3>
        <% @favorite_users.each do |user| %>
          <%= render 'user', user: user %>
        <% end %>
      </div>
    </div>

app/views/users/_like_button.html.erb
<div class="like-icon mx-2 <%= 'red' if current_user.favorited?(@user) %>" data-id="<%= @user.id %>">
  <i class="fas fa-heart"></i>
</div>

app/views/users/_shelf.html.erb
  <div data-controller="shelf-categories">
    <div class="categories-container">
      <div class="category-btn" data-action="click->shelf-categories#want" data-shelf-categories-target="want">
        Want to play
      </div>
      <div class="category-btn" data-action="click->shelf-categories#playing" data-shelf-categories-target="playing">
        Now Playing
      </div>
      <div class="category-btn" data-action="click->shelf-categories#completed" data-shelf-categories-target="complete">
        Completed
      </div>
    </div>
    <div id="wants" data-shelf-categories-target="wants" hidden>
      <%# <div class="game-cards"> %>
      <div class="row" data-shelf-categories-target="wantsRow">
        <% @want_to_play.each do |shelf_game| %>
          <div class="col-md-4 col-sm-6" data-shelf-categories-target="shelfcard" id='<%= shelf_game.id %>'>
            <div class="shelf-card" style="background-image: url('<%= shelf_game.game.image_url %>');">
              <div class="shelf-card-overlay">
                <div class="trash-container">
                  <%# empty for styling %>
                </div>
                <div class="shelf-game-title">
                  <h3>
                    <%= link_to game_path(shelf_game.game) do %>
                      <%= shelf_game.game.title %>
                    <% end %>
                  </h3>
                </div>
                <div class="shelf-buttons">
                    <%# empty for styling %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%# </div> %>
    </div>
    <div id="plays" data-shelf-categories-target="plays" hidden>
      <%# <div class="game-cards"> %>
      <div class="row" data-shelf-categories-target="playsRow">
        <% @now_playing.each do |shelf_game| %>
          <div class="col-md-4 col-sm-6"   data-shelf-categories-target="shelfcard" id='<%= shelf_game.id %>'>
            <!-- old cards
              <%= link_to game_path(shelf_game.game) do %>
                <div class="game-card">
                  <img src="<%= shelf_game.game.image_url %>" alt="Boxart for <%= shelf_game.game.title %>">
                  <div class="game-title">
                    <h3>
                      <%= shelf_game.game.title %>
                    </h3>
                  </div>
                </div>
              <% end %>
              -->
            <div class="shelf-card" style="background-image: url('<%= shelf_game.game.image_url %>');">
              <div class="shelf-card-overlay">
                <div class="trash-container">
                  <%# empty for styling %>
                </div>
                <div class="shelf-game-title">
                  <h3>
                    <%= link_to game_path(shelf_game.game) do %>
                      <%= shelf_game.game.title %>
                    <% end %>
                  </h3>
                </div>
                <div class="shelf-buttons">
                  <%# empty for styling %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%# </div> %>
    </div>
    <div id="completes" data-shelf-categories-target="completes" hidden>
      <%# <div class="game-cards"> %>
      <div class="row" data-shelf-categories-target="completesRow">
        <% @completed.each do |shelf_game| %>
          <div class="col-md-4 col-sm-6"   data-shelf-categories-target="shelfcard" id='<%= shelf_game.id %>'>
            <!-- old cards
              <%= link_to game_path(shelf_game.game) do %>
                <div class="game-card">
                  <img src="<%= shelf_game.game.image_url %>" alt="Boxart for <%= shelf_game.game.title %>">
                  <div class="game-title">
                    <h3>
                      <%= shelf_game.game.title %>
                    </h3>
                  </div>
                </div>
              <% end %>
              -->
            <div class="shelf-card" style="background-image: url('<%= shelf_game.game.image_url %>');">
              <div class="shelf-card-overlay">
                <div class="trash-container">
                  <%# empty for styling %>
                </div>
                <div class="shelf-game-title">
                  <h3>
                    <%= link_to game_path(shelf_game.game) do %>
                      <%= shelf_game.game.title %>
                    <% end %>
                  </h3>
                </div>
                <div class="shelf-buttons">
                    <%# empty for styling %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%# </div> %>
    </div>
  </div>

app/views/users/_user.html.erb
<div class="favorite" data-id="<%= user.id %>">
  <ul class="friend-list clearfix">
    <%= link_to user_path(user) do %>
    <li class="friend-info"><%= user.name %></li>
    <%if user.avatar.attached? %>
      <%= cl_image_tag(@user.avatar.key, class: "avatar")%>
    <% else %>
      <%= image_tag "gamepad.png", class: "avatar" %>
    <% end %>
  <% end %>
  </ul>
</div>

app/views/users/edit.html.erb
<%= render :partial => 'shared/navbar' %>

<div class="container-edit-form">
  <h2>
    Edit your profile
  </h2>

  <%= simple_form_for(current_user) do |f| %>
    <%= f.input :name, maxlength: 21 %>
    <%= f.input :avatar, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%if @user.avatar.attached? %>
        <%= cl_image_tag(@user.avatar.key, class: "avatar")%>
      <% else %>
        <%= image_tag "gamepad.png", class: "avatar" %>
      <% end %>
      <h1><%= @user.name %>'s profile</h1>
      <h1>Reviews</h1>
      <% @user.reviews.each do |review| %>
        <!-- this line needs to be put in the controller -->
        <% @game = Game.find(review.game.id) %>
        <div class="rounded-box-reviews col-lg-12 col-md-4">
          <ul class="list-group list-group-flush col-6">
            <p class ="review-user">
              <%= review.game.title %>
              <%= link_to "Visit", game_path(@game), class: 'btn btn-secondary btn-sm w-4px'  %>
              <% review.rating.times do %>
                <%= image_tag('icons/star-full.svg', class: "review-star") %>
              <% end %>
              <% (5 - review.rating).times do %>
                <%= image_tag('icons/star-empty.svg', class: "review-star") %>
              <% end %>
            </p>
            <p class ="review-time"> <small><%= time_ago_in_words(review.created_at) %> ago</small></p>
            <p class="review-content">"<%= review.content %>"</p>
          </ul>
          <%= image_tag @game.image_url, class: "review-image" %>
        </div>
      <% end %>
    </div>
    <div class="col-6">
      <div class="container">
        <div class="row">
          <% if @user != current_user  %>
            <div class="user-list col-sm-6">
              <h1>follow this user</h1>
              <div class="d-flex">
                <h3 class="follow-user"><%= @user.name  %>
                  <%= link_to toggle_favorite_user_path(@user), remote: true, method: :post do %>
                    <%= render 'users/like_button', user: @user %>
                  <% end %>
                </h3>
              </div>
            <% else %>
              <p></p>
            <% end %>
          </div>
          <% if @user == current_user %>
            <div class="col-6">
              <h1>Following users</h1>
              <div class="favorites">
                <% @favorite_users.each do |user| %>
                  <%= render 'user', user: user %>
                <% end %>
              </div>
            <% else %>
              <p></p>
            </div>
          <% end %>
        </div>
      </div>
      <div class="graph col-6">
        <h1>My shelf data</h1>
        <!-- adding data attribute -->
        <canvas id="myChart" width="220" height="220"
        data-page-views="<%=@graph_array %>">
        </canvas>
      </div>
    </div>
  </div>
</div>
<% unless @user.shelf_games.empty? %>
  <div class="container">
    <%= render 'users/shelf' %>
  </div>
<% end %>

app/views/users/toggle_favorite.js.erb
var userId = '<%= @user.id%>'


function toggleLikeButton(userId, favoritedUser) {
  console.log('clicked')
  let likeButton = document.querySelector(`.like-icon[data-id='${userId}']`)
  likeButton.classList.toggle('red');
  if (likeButton.classList.contains('red')) {
    const favoriteList = document.querySelector('.favorites');
    favoriteList.insertAdjacentHTML('beforeend', favoritedUser)
  }
  else {
    document.querySelector(`.favorite[data-id='${userId}']`).remove()
  }
}
toggleLikeButton(userId, '<%= j render "users/user", user: @user %>');