config/routes.rb
Rails.application.routes.draw do
  # changed for user profiles to appear
  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show, :index]

  # allows a user to like another user profile
  resources :users, only: :show do
    member do
      post 'toggle_favorite', to: "users#toggle_favorite"
    end
  end

  resources :shelf_games, only: [:index, :create, :update, :destroy]
  root to: 'games#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # If we decide to have user created shelves we should add :new and :create

  resources :games, only: [:index, :show] do
    resources :shelf_games, only: [:create, :update]

    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <% if user_signed_in? %>
    <%= link_to shelf_games_path(current_user), class: "navbar-brand" do %>
      <%= image_tag "logo2.png" %>
      <% end %>
  <% else %>
  <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo2.png" %>
    <% end %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%= form_tag games_path, method: :get, class: "form-inline" do %>
          <%= text_field_tag :query, params[:query], placeholder: "Search Games, Users" %>
          <%= submit_tag "Search", class: "btn search-btn my-2 my-sm-0" %>
        <% end %>
        <li class="nav-item dropdown">
        <%if current_user.avatar.attached? %>
          <%= cl_image_tag(current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
        <% else %>
          <%= image_tag "gamepad.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to 'View My Profile', shelf_games_path, class: "dropdown-item" %>
            <%= link_to "Edit My Profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Games", root_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
          <%= link_to "Login", new_user_session_path, class: 'btn search-btn my-2 my-sm-0' %>
          <%= link_to "Sign up", new_user_registration_path, class: 'btn search-btn my-2 my-sm-0' %>
      <% end %>
    </ul>
  </div>
</div>