config/routes.rb
Rails.application.routes.draw do
  # changed for user profiles to appear
  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show, :index]

  # allows a user to like another user profile
  resources :users, only: :show do
    member do
      post 'toggle_favorite', to: "users#toggle_favorite"
    end
  end

  resources :shelf_games, only: [:index, :create, :update, :destroy]
  root to: 'games#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # If we decide to have user created shelves we should add :new and :create

  resources :games, only: [:index, :show] do
    resources :shelf_games, only: [:create, :update]

    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/shelf_game.rb
class ShelfGame < ApplicationRecord
  belongs_to :user
  belongs_to :game

  validates :category, presence: true
end

app/controllers/shelf_games_controller.rb
class ShelfGamesController < ApplicationController
  def index
    # creates the link path to get the users show page
    @user = current_user
    @users = User.all
    shelf_games = policy_scope(ShelfGame).includes(:game).order(created_at: :desc)
    @favorite_users = current_user.favorited_by_type('User')
    @want_to_play = []
    @now_playing = []
    @completed = []
    shelf_games.each do |shelf_game|
      if shelf_game.category == 'want to play'
        @want_to_play << shelf_game
      elsif shelf_game.category == 'now playing'
        @now_playing << shelf_game
      elsif shelf_game.category == 'completed'
        @completed << shelf_game
      end
    end
    @user.reviews.each do |review|
      @game = Game.find(review.game.id)
    end
    # this shows the graph
    @game_per_category = @user.shelf_games.group_by{|game| game.category}
    @completed_number =  @game_per_category['completed'].to_a.count
    @now_playing_number =  @game_per_category['now playing'].to_a.count
    @want_to_play_number =  @game_per_category['want to play'].to_a.count
    @graph_array = [ @completed_number, @now_playing_number, @want_to_play_number ]
    # respond_to do |format|
    #   format.html
    #   format.js
    # end

    @user.shelf_games.each do |game|
      @category = game.category
      @latest_game = Game.find([game.game_id])
      @latest_game.each do |content|
        @title = content.title
        @image = content.image_url
        @updated_at = (content.updated_at)
      end
    end
  end

  def create
    @game = Game.find(params[:game_id])
    @shelf_game = ShelfGame.new(shelf_game_params)
    authorize @shelf_game
    @shelf_game.game = @game
    @shelf_game.user = current_user
    @shelf_game.save
    redirect_to game_path(@game)
  end

  def update
    @shelf_game = ShelfGame.find(params[:id])
    @game = Game.find(params[:game_id])
    authorize @shelf_game
    @shelf_game.update(shelf_game_params)
    @shelf_game.save
  end

  def destroy
    shelf_game = ShelfGame.find(params[:id])
    authorize shelf_game
    shelf_game.delete

    redirect_to shelf_games_path
  end

  private

  def shelf_game_params
    params.require(:shelf_game).permit(:category)
  end
end

app/views/shelf_games/_profile.html.erb
<div class="container">

<div class="username-on-profile">
  <h1><%if current_user.avatar.attached? %>
        <%= cl_image_tag(@user.avatar.key, class: "avatar")%>
      <% else %>
        <%= image_tag "gamepad.png", class: "avatar" %>
      <% end %><%= @user.name %>'s profile
  </h1>
</div>

  <div class="row">
    <div class="col-6">
<!-- This shows the user's reviews -->
      <h1>Reviews</h1>
      <% @user.reviews.each do |review| %>
        <div class="rounded-box-reviews">
              <b><%= link_to review.game.title, game_path(review.game), class: 'review-title' %></b>
              <%= image_tag review.game.image_url, class: "review-image" %>
              <div class="review-stars">
                <% review.rating.times do %>
                  <%= image_tag('icons/star-full.svg', class: "review-star") %>
                <% end %>
                <% (5 - review.rating).times do %>
                  <%= image_tag('icons/star-empty.svg', class: "review-star") %>
                <% end %>
                <div class ="review-time"><small><%= time_ago_in_words(review.created_at) %> ago</small></div>
              </div>
            <div class="my-review-content">
              "<%= review.content %>"
            </div>
        </div>
      <% end %>
    </div>

<!-- For visitor on user page - shows graph and Heart Button to follow -->
    <div class="col-6">
      <% if @user != current_user  %>
        <div class="user-list">
          <h1>follow this user</h1>
          <div class="d-flex">
          <h3 class="follow-user"><%= @user.name  %>
            <%= link_to toggle_favorite_user_path(@user), remote: true, method: :post do %>
              <%= render 'users/like_button', user: @user %>
            <% end %>
          </h3>
        </div>

      <!-- graph -->
        <h1>My shelf data</h1>
        <canvas id="myChart" data-page-views="<%=@graph_array %>"></canvas>
        <div class="graph"></div>
      <% end %>

<!-- For the user themself on their page - shows graph and other users they follow -->
      <% if @user == current_user %>
        <h1>Following</h1>
        <div class="followed-people">
        <% @favorite_users.each do |user| %>
          <div class="favorite" data-id="<%= user.id %>">
            <ul class="friend-list clearfix">
              <%= link_to user_path(user) do %>
              <li class="friend-img avatar">
                      <%if user.avatar.attached? %>
                        <%= cl_image_tag(user.avatar.key, class: "avatar")%>
                      <% else %>
                        <%= image_tag "gamepad.png", class: "avatar" %>
                      <% end %>
              </li>
                <li class="friend-info"><h4><%= user.name %></h4></li>
                  <li class="friend-info">Followers: <%= user.reviews.count %>, Games: <%= user.games.count%></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>

      <div class="latest-shelf-update-container">
        <h1>Latest shelf update</h1>
        <ul class="list-group latest-shelf-update">
          <li>
            <p class="shelf-update-title">
              <% @latest_game.each do |content| %>
              <%= content.title %>
            </p>
          </li>
          <li><%= image_tag content.image_url, class: "review-image" %></li>
              <% end %>
        </ul>
      </div>
      <!-- graph -->
        <h1>My shelf data</h1>
        <div class="graph"><canvas id="myChart" data-page-views="<%=@graph_array %>"></canvas></div>
      <% end %>

  </div>
</div>

app/views/shelf_games/index.html.erb
<%= render 'shelf_games/profile' %>
<div class="container">
  <div data-controller="shelf-categories">
    <div class="categories-container">
      <div class="category-btn" data-action="click->shelf-categories#want" data-shelf-categories-target="want">
        Want to play
      </div>
      <div class="category-btn" data-action="click->shelf-categories#playing" data-shelf-categories-target="playing">
        Now Playing
      </div>
      <div class="category-btn" data-action="click->shelf-categories#completed" data-shelf-categories-target="complete">
        Completed
      </div>
    </div>
    <div id="wants" data-shelf-categories-target="wants" hidden>
      <div class="row" data-shelf-categories-target="wantsRow">
        <% @want_to_play.each do |shelf_game| %>
          <div class="col-md-4 col-sm-6" data-shelf-categories-target="shelfcard" id='<%= shelf_game.id %>'>
            <div class="shelf-card" style="background-image: url('<%= shelf_game.game.image_url %>');">
              <div class="shelf-card-overlay">
                <div class="trash-container">
                  <%= link_to shelf_game_path(shelf_game), method: :delete, data: { confirm: "Are you sure?" } do %>
                    <%= image_tag('icons/trash.svg', class: 'trash-icon') %>
                  <% end %>
                </div>
                <div class="shelf-game-title">
                  <h3>
                    <%= link_to game_path(shelf_game.game) do %>
                      <%= shelf_game.game.title %>
                    <% end %>
                  </h3>
                </div>
                <div class="shelf-buttons">
                  <div class="shelf-btn">
                    <%# empty for styling %>
                  </div>
                  <div class="shelf-btn">
                    <%= simple_form_for(shelf_game, remote: true, data: { shelf_categories_target: "form", action: 'submit->shelf-categories#updateCategory'}) do |f| %>
                      <%= hidden_field_tag :game_id, shelf_game.game.id %>
                      <%= f.hidden_field :category, value: 'now playing' %>
                      <%= f.submit ">>", class: 'shelf-submit' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div id="plays" data-shelf-categories-target="plays" hidden>
      <%# <div class="game-cards"> %>
      <div class="row" data-shelf-categories-target="playsRow">
        <% @now_playing.each do |shelf_game| %>
          <div class="col-md-4 col-sm-6"   data-shelf-categories-target="shelfcard" id='<%= shelf_game.id %>'>
            <!-- old cards
              <%= link_to game_path(shelf_game.game) do %>
                <div class="game-card">
                  <img src="<%= shelf_game.game.image_url %>" alt="Boxart for <%= shelf_game.game.title %>">
                  <div class="game-title">
                    <h3>
                      <%= shelf_game.game.title %>
                    </h3>
                  </div>
                </div>
              <% end %>
              -->
            <div class="shelf-card" style="background-image: url('<%= shelf_game.game.image_url %>');">
              <div class="shelf-card-overlay">
                <div class="trash-container">
                  <%= link_to shelf_game_path(shelf_game), method: :delete, data: { confirm: "Are you sure?" } do %>
                    <%= image_tag('icons/trash.svg', class: 'trash-icon') %>
                  <% end %>
                </div>
                <div class="shelf-game-title">
                  <h3>
                    <%= link_to game_path(shelf_game.game) do %>
                      <%= shelf_game.game.title %>
                    <% end %>
                  </h3>
                </div>
                <div class="shelf-buttons">
                  <div class="shelf-btn">
                    <%= simple_form_for(shelf_game, remote: true, data: { shelf_categories_target: "form", action: 'submit->shelf-categories#updateCategory' }) do |f| %>
                      <%= hidden_field_tag :game_id, shelf_game.game.id %>
                      <%= f.hidden_field :category, value: 'want to play' %>
                      <%= f.submit "<<", class: 'shelf-submit' %>
                    <% end %>
                  </div>
                  <div class="shelf-btn">
                    <%= simple_form_for(shelf_game, remote: true, data: { shelf_categories_target: "form", action: 'submit->shelf-categories#updateCategory' }) do |f| %>
                      <%= hidden_field_tag :game_id, shelf_game.game.id %>
                      <%= f.hidden_field :category, value: 'completed' %>
                      <%= f.submit ">>", class: 'shelf-submit' %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%# </div> %>
    </div>
    <div id="completes" data-shelf-categories-target="completes" hidden>
      <%# <div class="game-cards"> %>
      <div class="row" data-shelf-categories-target="completesRow">
        <% @completed.each do |shelf_game| %>
          <div class="col-md-4 col-sm-6"   data-shelf-categories-target="shelfcard" id='<%= shelf_game.id %>'>
            <!-- old cards
              <%= link_to game_path(shelf_game.game) do %>
                <div class="game-card">
                  <img src="<%= shelf_game.game.image_url %>" alt="Boxart for <%= shelf_game.game.title %>">
                  <div class="game-title">
                    <h3>
                      <%= shelf_game.game.title %>
                    </h3>
                  </div>
                </div>
              <% end %>
              -->
            <div class="shelf-card" style="background-image: url('<%= shelf_game.game.image_url %>');">
              <div class="shelf-card-overlay">
                <div class="trash-container">
                  <%= link_to shelf_game_path(shelf_game), method: :delete, data: { confirm: "Are you sure?" } do %>
                    <%= image_tag('icons/trash.svg', class: 'trash-icon') %>
                  <% end %>
                </div>
                <div class="shelf-game-title">
                  <h3>
                    <%= link_to game_path(shelf_game.game) do %>
                      <%= shelf_game.game.title %>
                    <% end %>
                  </h3>
                </div>
                <div class="shelf-buttons">
                  <div class="shelf-btn">
                    <%= simple_form_for(shelf_game, remote: true,  data: { shelf_categories_target: "form", action: 'submit->shelf-categories#updateCategory' }) do |f| %>
                      <%= hidden_field_tag :game_id, shelf_game.game.id %>
                      <%= f.hidden_field :category, value: 'now playing' %>
                      <%= f.submit "<<", class: 'shelf-submit' %>
                    <% end %>
                  </div>
                  <div class="shelf-btn">
                    <%# empty for styling %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <%# </div> %>
    </div>
  </div>
</div>