config/routes.rb
Rails.application.routes.draw do
  # changed for user profiles to appear
  devise_for :users, :path_prefix => 'd'
  resources :users, :only => [:show, :index]

  # allows a user to like another user profile
  resources :users, only: :show do
    member do
      post 'toggle_favorite', to: "users#toggle_favorite"
    end
  end

  resources :shelf_games, only: [:index, :create, :update, :destroy]
  root to: 'games#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # If we decide to have user created shelves we should add :new and :create

  resources :games, only: [:index, :show] do
    resources :shelf_games, only: [:create, :update]

    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many :shelf_games, dependent: :destroy

  validates :title, presence: true
  validates :genre, presence: true
  validates :console, presence: true
  validates :release_date, presence: true


  include PgSearch::Model
  pg_search_scope :search_by_title_and_genre,
    against: [ :title, :genre ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/games_controller.rb
require 'json'
require 'net/http'
require 'uri'
require 'google/apis/youtube_v3'
require 'active_support/all'
# GOOGLE_API_KEY=ENV['GOOGLE_API_KEY']

class GamesController < ApplicationController
  # helper_method :find_videos
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @users = User.all
    # creates the link path to get the users show page
    @user = current_user
    # for the search bar
    if params[:query].present?
      @games = policy_scope(Game).search_by_title_and_genre(params[:query])
    else
      @games = Game.all
      @games = policy_scope(Game).order(release_date: :desc)
    end
    # allows searches for users in the nav searchbar
    if params[:query].present?
      @users = policy_scope(User).search_by_name(params[:query])
    else
    @users = User.all
    @users = policy_scope(User).order(created_at: :desc)
  end
  end

  def show
    # creates the link path to get the users show page
    @user = current_user
    @games = Game.all
    @game = Game.find(params[:id])
    authorize @game
    @streams = get_twitch_streams(@game.title)
    unless @streams.empty?
      @preview_stream = @streams.first
      thumbnail_url_split = @preview_stream['thumbnail_url'].split(/{width}x{height}/)
      @thumbnail_url = thumbnail_url_split.join("500x300")
    end
    # if the user is not signed in they cannot add a game to a list
    if user_signed_in?
      # list_game is either present with an id or not yet made
      @shelf_game = current_user.shelf_games.find_by(game: @game) || ShelfGame.new
      # You need this to make a new review in the show page
    end
    @review = Review.new
    ratings = []
    @rating = 0
    @game.reviews.each do |review|
      ratings << review.rating
    end
    @rating = ratings.sum / ratings.length unless ratings.empty?
    # still not perfect but much better than before
    recommended_games = recommended(@game)
    @three_games = recommended_games.keys.first(3)

    # gets the youtube trailer from the youtube api
    # @youtube_results = find_videos("#{@game.title} game release trailer")
    # @one_game = @youtube_results.first.to_h
    # @one_game_id = @one_game[:id][:video_id]
  end


  private

  def find_videos(keyword, after: 80.months.ago, before: Time.now)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = ENV['GOOGLE_API_KEY']
    next_page_token = nil
    opt = {q: keyword}
    results = service.list_searches(:snippet, q: keyword)
    results.items.each do |item|
      id = item.id
    end
  end

  def get_tags(game)
    game_tags = []
    game.genre.split(",").each do |genre|
      game_tags << genre
    end
    # comment out to test off heroku from here -->
    game.developer.split(",").each do |dev|
      game_tags << dev
    end
    # <-- to here
    return game_tags
  end

  def tally_recommendations(games_array)
    # tallies the games into a hash and organizes it by highest tally first
    return games_array.tally.sort_by { |_key, value| -value }.to_h
  end

  def recommended(game)
    all_games = Game.all
    game_tags = get_tags(game)
    recommended_games = []
    # check for each tag in each other game
    game_tags.each do |tag|
      all_games.each do |current_game|
        tags = get_tags(current_game)
        recommended_games << current_game if tags.include?(tag) && current_game.title != game.title
      end
    end
    return tally_recommendations(recommended_games)
  end

  def get_twitch_streams(game)
    game_query = game.downcase
    uri = URI.parse("https://api.twitch.tv/helix/games?name=#{game_query}")
    request = Net::HTTP::Get.new(uri)
    request["Client-Id"] = ENV['TWITCH_CLIENT_ID']
    request["Authorization"] = "Bearer #{ENV['TWITCH_TOKEN']}"

    req_options = {
      use_ssl: uri.scheme == "https",
    }

    response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
      http.request(request)
    end
    resp = JSON.parse(response.body)["data"]
    if resp.first.nil?
      return []
    end
    game_id = resp.first['id']

    stream_uri = URI.parse("https://api.twitch.tv/helix/streams?game_id=#{game_id}")
    stream_request = Net::HTTP::Get.new(stream_uri)
    stream_request["Client-Id"] = ENV['TWITCH_CLIENT_ID']
    stream_request["Authorization"] = "Bearer #{ENV['TWITCH_TOKEN']}"

    req_options = {
      use_ssl: stream_uri.scheme == "https",
    }

    stream_response = Net::HTTP.start(stream_uri.hostname, stream_uri.port, req_options) do |http|
      http.request(stream_request)
    end
    stream_resp = JSON.parse(stream_response.body)["data"]
    return stream_resp

    # if !resp.empty?
    #   user = resp.select{ |user| user["broadcaster_login"] == "#{query}" }[0]
    #   p user
    #   if user["is_live"] == true
    #     return "El usuario #{query} está transmitiendo en vivo jugando #{user["game_name"]}!!! 🔴\nMíralo en https://www.twitch.tv/#{query}"
    #   else
    #     return "El usuario #{query} no está transmitiendo en este momento, en su última transmición jugó #{user["game_name"]}.\nSíguelo en https://www.twitch.tv/#{query}"
    #   end
    # else
    #   return "#{query}? Quién te conoce papá?."
    # end
  end
end

app/views/games/_categories.html.erb
<div class="categories">
  <div class="categories-links">
<%= form_tag games_path, method: :get, class: "form-inline genre-form" do %>
          <input type="hidden"  name='query' value='puzzle'/>
          <%= submit_tag "Puzzle", class: "btn btn-ghost" %>
        <%end%>
        <%= form_tag games_path, method: :get, class: "form-inline genre-form" do %>
          <input type="hidden"  name='query' value='action'/>
          <%= submit_tag "action", class: "btn btn-ghost" %>
        <%end%>
<%= form_tag games_path, method: :get, class: "form-inline genre-form" do %>
          <input type="hidden"  name='query' value='adventure'/>
          <%= submit_tag "adventure", class: "btn btn-ghost" %>
        <%end%>
<%= form_tag games_path, method: :get, class: "form-inline genre-form" do %>
          <input type="hidden"  name='query' value='RPG'/>
          <%= submit_tag "RPG", class: "btn btn-ghost" %>
        <%end%>
<%= form_tag games_path, method: :get, class: "form-inline genre-form" do %>
          <input type="hidden"  name='query' value='Indie'/>
          <%= submit_tag "Indie", class: "btn btn-ghost" %>
        <%end%>
        <%= form_tag games_path, method: :get, class: "form-inline genre-form" do %>
          <input type="hidden"  name='query' value='platform'/>
          <%= submit_tag "platform", class: "btn btn-ghost" %>
        <%end%>
                <%= form_tag games_path, method: :get, class: "form-inline genre-form" do %>
          <input type="hidden"  name='query' value='adventure'/>
          <%= submit_tag "adventure", class: "btn btn-ghost" %>
        <%end%>
                      <%= form_tag games_path, method: :get, class: "form-inline genre-form" do %>
          <input type="hidden"  name='query' value='casual'/>
          <%= submit_tag "casual", class: "btn btn-ghost" %>
        <%end%>
                    <%= form_tag games_path, method: :get, class: "form-inline genre-form" do %>
          <input type="hidden"  name='query' value='shooter'/>
          <%= submit_tag "shooter", class: "btn btn-ghost" %>
        <%end%>
  </div>
</div>

app/views/games/index.html.erb
<div class="container">
<!-- categories partial -->
<%= render 'games/categories' %>
  <div class="row">
  <% if params[:query].blank? %>
    <h1 class="search-game-results"><%= pluralize @games.count, 'game' %> available</h1>
  <% else %>
    <h1 class="search-game-results"><%= pluralize @games.count, 'result' %> for <em><%= params[:query] %></em></h1>
  <% end %>
    <% @games.each do |game| %>
      <div class="col-md-4 col-sm-6">
        <%= link_to game_path(game) do %>
          <div class="game-card">
            <img src="<%= game.image_url %>" alt="Boxart for <%= game.title %>">
            <div class="game-title">
              <h3>
                <%= game.title %>
              </h3>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <!--Shows users when searched for in the navbar -->
  <% if params[:query].present?%>
    <div class="user-container w-720px">
      <div class="search-container w-720px ">
          <% @users.each do |user| %>
            <div class="d-flex align-items-center">
              <%= link_to user_path(user) do %>
                <div class="image">
                  <% if user.avatar.attached? %>
                    <%= cl_image_tag(user.avatar.key, class: "rounded m-2", width: "80px")%>
                  <% end %>
                <% end %>
              </div>
              <div class="ml-3 w-100">
                <%= link_to user_path(user) do %>
                  <h4 class="mb-0 mt-0"><%= user.name %></h4>
                <% end %>
                <div class="p-2 mt-2 bg-secondary d-flex flex-row rounded text-white stats">
                  <div class="d-flex flex-column">
                    <div class="p-2">Reviews: <%= user.reviews.count %></div>
                  </div>
                  <div class="d-flex flex-column">
                    <div class="p-2">Followers: <%= user.favorited.count%></div>
                  </div>
                  <div class="d-flex flex-column">
                    <div class="p-2">Games: <%= user.games.count%></div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
  <% end %>
    </div>

app/views/games/show.html.erb
<div class="container">

  <div class="game-row-first">
    <div class="col-lg-8 col-sm-12">
      <%= image_tag @game.image_url, class: "show-game-image" %>
    </div>

    <div class="col-lg-4 col-sm-12">
      <div class="card ratings-card p-2">
      <h2 class="game-title"><%= @game.title %></h2>
        <div class="star-container">
          <% @rating.times do %>
            <%= image_tag('icons/star-full.svg', class: "star rating") %>
          <% end %>
          <% if @rating == 0 %>
            <p class="rating-notification">
              Be the First to Rate!
            </p>
            <% (5 - @rating).times do %>
              <%= image_tag('icons/star-empty.svg', class:"star no-rating") %>
            <% end %>
          <% else %>
            <% (5 - @rating).times do %>
              <%= image_tag('icons/star-empty.svg', class: "star rating-remainder") %>
            <% end %>
          <% end %>
        </div>

        <% if user_signed_in? %>
          <!--adding games to users' shelves-->
          <div data-controller="show-button">
            <p class="add-shelf-label">Add to My Game Shelf</p>
            <div class ="shelf-buttons-container">
              <%= simple_form_for([@game, @shelf_game], remote: true, data: {show_button_target: "want", action: "submit->show-button#change"}) do |f| %>
                <%= f.input :category, input_html:{value:"want to play"}, as: :hidden %>
                <%= f.button :submit, "Want to play", class: "btn #{(@shelf_game.category == 'want to play') ? 'btn-outline-primary' : 'btn-primary'}" %>
              <% end %>
              <%= simple_form_for([@game, @shelf_game], remote: true, data: {show_button_target: "play", action: "submit->show-button#change"}) do |f| %>
                <%= f.input :category, input_html:{value:"now playing"}, as: :hidden %>
                <%= f.button :submit, "Now playing", class: "btn #{(@shelf_game.category == 'now playing') ? 'btn-outline-primary' : 'btn-primary'}" %>
              <% end %>
              <%= simple_form_for([@game, @shelf_game], remote: true, data: {show_button_target: "complete", action: "submit->show-button#change"} ) do |f| %>
                <%= f.input :category, input_html:{value:"completed"}, as: :hidden %>
                <%= f.button :submit, "Completed", class: "btn #{(@shelf_game.category == 'completed') ? 'btn-outline-primary' : 'btn-primary'}"%>
              <% end %>
            </div>
            <!--Checking status of game (make into a partial) -->
            <!--persisted checks if it is saved -->
            <% if @shelf_game.persisted? %>
              <div data-show-button-target="content" class="show-shelf-content">
                This game is on your shelf under <%= @shelf_game.category %>
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="twitch-preview-container">
          <% if @streams.empty? %>
            <div class="twitch-no-preview">
              No one is streaming <%= @game.title %> right now...
              <br>
              Come back later! <%= image_tag('icons/twitch.svg', class: 'twitch-icon') %>
            </div>
          <% else %>
              <a href="https://www.twitch.tv/<%= @preview_stream['user_login'] %>" class="twitch-preview" target="_blank">
                Watch <%= @preview_stream['user_name'] %> play <%= @game.title %> <%= image_tag('icons/twitch.svg', class: 'twitch-icon') %>
              <%= image_tag(@thumbnail_url, class: 'preview-thumbnail') %>
              </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="game-row-second-left">
        <p><em><%= @game.genre.split(",").join(", ")%></em></p>
        <p><b><%= @game.developer.split(",").join(", ")%></b></p>
        <p><%= @game.console.split(",").join(", ")%></p>
        <p><%= truncate(@game.description, length: 1070) %></p>
      </div>
    </div>
    <!-- youtube trailer -->
    <div class="col-6">
      <div class="game-row-second-right">
        <iframe width="100%" height="397"
      src="https://www.youtube.com/embed/<%= @one_game_id %>?controls=1&mute=1", class="trailer-image">
        </iframe>
      </div>
    </div>
  </div>

  <div class="game-row-reviews">
    <% if user_signed_in? %>
      <h3>Leave a review for <%= @game.title %></h3>
      <!--partial for the review form -->
      <%= render 'reviews/form', game: @game, review: @review %>
    <% end %>
    <!--partial for the shelf of reviews -->
    <br>
    <h4>Reviews from other users</h4>
    <%= render 'reviews/review' %>
  </div>

  <h3>You may also like</h3>
  <div class="recommended-game-cards">
    <!-- Recommends (max) 3 games by genre not including current game -->
    <% @three_games.each do |game| %>
      <%= link_to game_path(game) do %>
        <div class="game-card">
          <img src="<%= game.image_url %>" alt="Boxart for <%= game.title %>">
          <h3>
            <%= game.title %>
          </h3>
        </div>
      <% end %>
    <% end %>
  </div>
</div>